### ISSUE TITLE
Latest scrape time and success/fail status

### ISSUE THREAD

**Issue by joehealy** [benkaiser/covid-vic-exposure-map#1]
Would be great to get an indication of the scrape time and whether or not it succeeded, also the total number of sites.
Also the time of the latest government addition.

Love it btw

**Comment by benkaiser** [comment]
Yes, this is my plan after work today. I'd like to make it scrape every 10 minutes and update a timestamp in the footer.

**Comment by benkaiser** [comment]
Added frequent scheduled action, but github seems to run it roughly hourly.
