### ISSUE TITLE
Filtering by time seems to trigger errors.

### ISSUE THREAD

**Issue by spiltcoffee** [benkaiser/covid-vic-exposure-map#10]
Had (different) errors occur in Firefox and Edge Chromium.

### Firefox
Clicked `Last 24 Hours`, `Last 3 Days` or `Last 7 Days`
```
Uncaught TypeError: i is undefined
    pad LatLngBounds.js:90
    drawMap (index):194
    <anonymous> (index):205
    EventListener.handleEvent* (index):205
```

### Edge Chromium
Clicked `Last 24 Hours` (`Last 3 Days` and `Last 7 Days` appears to be working fine)
```
Uncaught TypeError: Cannot read property 'lat' of undefined
    at R.pad (LatLngBounds.js:90)
    at drawMap ((index):194)
    at HTMLButtonElement.<anonymous> ((index):204)
```

**Comment by benkaiser** [comment]
Thanks, I'll drill into what's happening here.

For Chrome/Edge Chromium, I think it's literally that there are just no locations in the last 24 hours added... could be wrong

**Comment by spiltcoffee** [comment]
I suspect that might be the case too. Guess just need not to call whatever lower function is throwing errors if there's no locations, I suppose.

**Comment by benkaiser** [comment]
Fixed both issues. Looks like the data parsing was a little more forgiving in Chrome than Firefox, so I fixed that up.
As for the Chromium error, I just no-opped the auto-zoom on the map when there were no markers (that was why it was throwing an error)
