### ISSUE TITLE
[Feature] Collapsible info box

### ISSUE THREAD

**Issue by spiltcoffee** [benkaiser/covid-vic-exposure-map#12]
The info box is kinda taking up a big chunk of space on a mobile screen. Would be nice to be able to collapse it.

![Screenshot_20210602-120020](https://user-images.githubusercontent.com/3926298/120412595-277fd100-c39a-11eb-8bfb-4a5255f8cd99.png)

**Comment by benkaiser** [comment]
Yeah good call, should be relatively simple
