### ISSUE TITLE
Geolocation Pin - PTV Bus 412

### ISSUE THREAD

**Issue by Lockxish** [benkaiser/covid-vic-exposure-map#13]
Hey Ben,

The below pin's going out the middle of nowhere. Should be somewhere in/between footscray/altona
![image](https://user-images.githubusercontent.com/85085615/120744695-e8d74b80-c53e-11eb-9802-1957b9631f41.png)

Thanks for resolving the refresh the other day, it appears to have resolved all the others.

**Comment by benkaiser** [comment]
I did a re-run on my machine and it looks like that one is fixed now, I did have to fix another PTV 412 pin though
