### ISSUE TITLE
Locations added 4/6/2021 missing

### ISSUE THREAD

**Issue by Lockxish** [benkaiser/covid-vic-exposure-map#14]
Hey Ben,

Anything added today (4/6/21) are missing from the map. I've got a last update time of 1:51 and there's 7 new sites added at 11:05 in the source data.
![image](https://user-images.githubusercontent.com/85085615/120745150-dc9fbe00-c53f-11eb-8149-bfbb7cac6070.png)

**Comment by benkaiser** [comment]
I re-ran again locally and it seems to be picking them up now
