### ISSUE TITLE
Exposure site with "Building Number" addresses not mapped

### ISSUE THREAD

**Issue by wigsofoz** [benkaiser/covid-vic-exposure-map#15]
Comparing the [exposure map](https://benkaiser.github.io/covid-vic-exposure-map/) for Richmond (accessed this morning, 6 September 2021), with the [exposure sites source data](https://www.coronavirus.vic.gov.au/case-alerts%E2%80%93public-exposure-sites) list, there are exposure site(s) for business addresses which are missing from the map view.

![image](https://user-images.githubusercontent.com/5275120/132143289-b0f95e9c-95e5-4b66-9123-be2414be7ae0.png)

For example, the current exposure site is missing from the above "all time" map view:
- `Building 8, 658 Church Street Richmond VIC 3121`

Google Maps shows 658 Church Street to be adjacent to the Yarra River.
![image](https://user-images.githubusercontent.com/5275120/132143357-f3f55322-7db1-4404-99b9-2674950197ee.png)

**Comment by benkaiser** [comment]
Hey @wigsofoz, I've updated the lat/lon of these 10 exposures manually. The Azure geocoding service isn't quite a robust as Google.
