### ISSUE TITLE
Missing site.

### ISSUE THREAD

**Issue by korg** [benkaiser/covid-vic-exposure-map#2]
This is fantastic. It is so annoying the gov site does not have a map version of the data, so great work.

But there is at least 1 missing site.

goto:
https://www.coronavirus.vic.gov.au/exposure-sites
search for suburb: glen iris

that returns:

Glen Iris | Coles Tooronga VillageTooronga RoadGlen Iris&nbsp;VIC&nbsp;3146 | 23/05/2021 4:00pm - 4:30pm | Case attended venue | 29/05/2021 | Tier 2 - Get tested urgently and isolate until you have a negative result
-- | -- | -- | -- | -- | --

The data says it was added to the source on the 29th.

Goto the map.

Map says data from the 30th, but the location isnt plotted.

**Comment by korg** [comment]
It isnt in the data.json in the repo (dated 35 mins ago as of 4:24pm Melb time)


If i pull the data manually with:

wget 'https://www.coronavirus.vic.gov.au/sdp-ckan?resource_id=afb52611-6061-4a2b-9110-74c920bede77&limit=10000'

then it is present.


So unless it was added in the last 35 mins (which the gov site says it was added on the 29th) then it might be worth investigating.

**Comment by benkaiser** [comment]
Fixed, looks like it may have returned previously from the API as a different piece of data, and so it was using the cache instead of the fresh API data. I've changed it to overlay the fresh API data on top of the cache.

Thanks for finding @korg !
