### ISSUE TITLE
Fairy Hills Kindergarten geolocation

### ISSUE THREAD

**Issue by joehealy** [benkaiser/covid-vic-exposure-map#4]
Not sure how much you are focusing on this (may be too much work for you), but placed in Altona instead of Ivanhoe.

![Screenshot from 2021-05-31 10-31-22](https://user-images.githubusercontent.com/2563935/120125408-097c6a00-c1fc-11eb-93fb-4a93217e8ed3.png)

**Comment by benkaiser** [comment]
Fixed!... Need to automate this correction process
