### ISSUE TITLE
GeoLocation Pin - Dandenong showing as Hot Springs, no hot springs pin

### ISSUE THREAD

**Issue by Lockxish** [benkaiser/covid-vic-exposure-map#6]
Hey Ben,

One of the locations in Dandenong is coming up as the Peninsula Hot Springs. And there's no pin where the hotsprings are

![image](https://user-images.githubusercontent.com/85085615/120125946-f9658a00-c1fd-11eb-9ea6-c4916e4c9c80.png)

**Comment by Lockxish** [comment]
Further to that, there's two other issue pins in Dandenong
![image](https://user-images.githubusercontent.com/85085615/120126047-4f3a3200-c1fe-11eb-9cb6-d76870e0982e.png)

![image](https://user-images.githubusercontent.com/85085615/120126053-58c39a00-c1fe-11eb-8b2b-7733fed62d4b.png)

**Comment by benkaiser** [comment]
Fixed, thanks for reporting @LachlanDowning
