### ISSUE TITLE
Sky High Mt. Dandenong is showing as Zimmerman Chadstone

### ISSUE THREAD

**Issue by chrisjbillington** [benkaiser/covid-vic-exposure-map#9]
Hi there, thanks for the great map.

Noticed an issue: when I click on the marker for Sky High in Mt. Dandenong, the popup instead shows Zimmerman Chadstone:

![image](https://user-images.githubusercontent.com/1044087/120185261-f8256480-c1df-11eb-8136-17d1bb5258da.png)

**Comment by benkaiser** [comment]
Fixed!

**Comment by chrisjbillington** [comment]
Thanks :)
